
sheets:
  range: A3:P
  emailRange: C3:C
  contactNumberRange: D3:D
  loginInfoRange: loginInfo!A2:B
  
mail:
   smtpHost: smtp.office365.com
   smtpPort: 587
   userName: xworkzdev@outlook.com
   password: KeepIT@Temp789
    
login: 
  userFile: classpath:users.yml
  sheetId: 1p3G4et36vkzSDs3W63cj6qnUFEWljLos2HHXIZd78Gg
  cookieDomain: localhost

